#!/usr/bin/env python
import os
import sys

env = SConscript("godot-cpp/SConstruct")

# For reference:
# - CCFLAGS are compilation flags shared between C and C++
# - CFLAGS are for C-specific compilation flags
# - CXXFLAGS are for C++-specific compilation flags
# - CPPFLAGS are for pre-processor flags
# - CPPDEFINES are for pre-processor defines
# - LINKFLAGS are for linking flags

# tweak this if you want to use different folders, or more folders, to store your source code in.
env.Append(CPPPATH=["src/"])
env['CC'] = env['CXX'] # because of the C code it tries to be "smart"
sources = Glob("../export-cli/matte/src/*.c")
sources += Glob("../export-cli/matte/src/rom/native.c")
sources += Glob("src/*.cpp")

env.Append(CPPFLAGS=["-DMATTE_USE_SYSTEM_EXTENSIONS", "-DMATTE_USE_SYSTEM_EXTENSIONS__BASIC"])
env.Append(CXXFLAGS=["-lm", "-lpthread"])

if env["platform"] == "macos":
    library = env.SharedLibrary(
        "project/bin/matte.{}.{}.framework/matte.{}.{}".format(
            env["platform"], env["target"], env["platform"], env["target"]
        ),
        source=sources,
    )
elif env["platform"] == "ios":
    if env["ios_simulator"]:
        library = env.StaticLibrary(
            "project/bin/matte.{}.{}.simulator.a".format(env["platform"], env["target"]),
            source=sources,
        )
    else:
        library = env.StaticLibrary(
            "project/bin/matte.{}.{}.a".format(env["platform"], env["target"]),
            source=sources,
        )
else:
    library = env.SharedLibrary(
        "project/bin/matte{}{}".format(env["suffix"], env["SHLIBSUFFIX"]),
        source=sources,
    )

Default(library)
