const VIEW_WIDTH  = 80;
const VIEW_HEIGHT = 22;
const CHAR_FONT_WIDTH_PX = 16;

const SELECTION_MODE__PEN = 0;
const SELECTION_MODE__RECTANGLE = 1;


const BACKGROUND_COLOR = "#303030";
const TEXT_COLOR_ACTIVE = "#afafaf";
const TEXT_COLOR_INACTIVE = "#505050";
const MAX_WIDTH = 512;

const BUTTON_COLOR_ACTIVE   = "#b0b0b0"
const BUTTON_COLOR_INACTIVE = "#606060"
