const VIEW_WIDTH  = 80;
const VIEW_HEIGHT = 22;
const CHAR_FONT_WIDTH_PX = 16;

const SELECTION_MODE__PEN = 0;
const SELECTION_MODE__RECTANGLE = 1;


const BACKGROUND_COLOR = "#303030";
const TEXT_COLOR_ACTIVE = "#afafaf";
const TEXT_COLOR_INACTIVE = "#505050";
const TEXT_COLOR_WALL = "#90ff90";
const TEXT_COLOR_SELECT = "#afafff";
const TEXT_COLOR_SELECT_INACTIVE = "#5f5faf";

const TEXT_COLOR_CONNECTION = "#9090ff";
const TEXT_COLOR_OBJECT = "#ff9090";
const TEXT_COLOR_EVENT = "#ff90ff";
const TEXT_COLOR_MARKER = "#ffff90";



const MAX_LENGTH = 256;

const BUTTON_COLOR_ACTIVE   = "#b0b0b0"
const BUTTON_COLOR_INACTIVE = "#606060";



